### ISSUE TITLE
[Bug]  Unbound [HttpClientCall] is deprecated. Consider using [request<HttpResponse>(builder)] instead.

### ISSUE THREAD

**Issue by Fallenstedt** [StarryBlueSky/Penicillin#27]
**Bug Type / Bug の種類:**
- [x] Uncaught exceptions / キャッチされていない例外
- [ ] Related to Model Class / モデルクラス関連
- [ ] Others / その他

**Description / 概要:**  
I am trying to get my tweets with `userTimelineByScreenName`
https://docs.nephy.jp/javadoc/penicillin/jp.nephy.penicillin.endpoints.timeline/user-timeline-by-screen-name.html

When I invoke this function, I get an error

```
ERROR [2020-02-16 03:38:56,989] Penicillin.ApiAction: Failed to request API. (https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=Fallenstedt&count=5&tweet_mode=extended, 1/3)
! java.lang.IllegalStateException: Unbound [HttpClientCall] is deprecated. Consider using [request<HttpResponse>(builder)] instead.
! at io.ktor.client.call.UtilsKt.call(utils.kt:32)
! at jp.nephy.penicillin.core.request.action.ActionKt.execute(Action.kt:146)
! at jp.nephy.penicillin.core.request.action.JsonArrayApiAction.invoke(JsonArrayApiAction.kt:42)
! at jp.nephy.penicillin.extensions.ApiActionKt.await(ApiAction.kt:47)
! at jp.nephy.penicillin.extensions.ApiActionKt$complete$1.invokeSuspend(ApiAction.kt:154)
! at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
! at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
! at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
! at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
! at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
! at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

The deprecation comes from ktor: 
https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/common/src/io/ktor/client/call/HttpClientCall.kt#L121-L131

I think we are using ktor here
https://github.com/NephyProject/Penicillin/blob/master/src/main/kotlin/jp/nephy/penicillin/core/request/action/Action.kt#L59

どのような Bug であるのかを明確かつ簡潔に説明してください。  

The bug occurs in my dropwizard application. I run `curl "localhost:8080/sentiment/calculate?name=Fallenstedt"` You can find the code used here: 
https://github.com/Fallenstedt/dropwizard-calc/blob/master/src/main/kotlin/to/dev/example/resources/SentimentResource.kt

**Environment / 環境:**  
Please complete the following information to specify the problem.  
問題を特定するために以下の情報を埋めてください。  

 - OS: macOS Mojave 
 - Java Version: Java 8
 - Penicillin Version: 4.2.3
 - Kotlin Version: 1.3.61
 - Twitter Application: Read only

**Additional context / 備考:**  
You can clone my project and follow the instructions in the readme to reproduce this bug. I don't know if I am doing something wrong, or if penicillin is using deprecated ktor methods.

**Comment by pois0** [comment]
It seems to have been fixed on the current master. Please wait until next release.
If you still have a problem, please let us know.
