### ISSUE TITLE
Characters escape issue

### ISSUE THREAD

**Issue by glanium** [StarryBlueSky/Penicillin#36]
in Japanese OK?

日本語で大丈夫でしょうか？？

Twitter APIでは&などの文字は\&amp;などと名前文字参照されて返されるのですが、
StatusクラスのtextRawやfullTextRawでは勝手に？？元の文字に置換されて返されます。
textRawなどは元の文字に置換される一方、StatusEntityなどの開始インデックス、終了インデックスを表すプロパティは
そのまま返されるのでずれてしまいす。

どっちかに合わせてもらえると幸いです

よろしくお願いします

**Comment by SlashNephy** [comment]
報告ありがとうございます！

ご指摘の通り、レスポンスを受け取った時点でHTML参照文字がアンエスケープされていました。
https://github.com/StarryBlueSky/Penicillin/blob/5832b3e9331a0b70405ed613d042a7057ad89370/src/commonMain/kotlin/blue/starry/penicillin/core/request/action/Action.kt#L113

これについてはアンエスケープする位置をタイミングを変更したいと思います。`Status#text` プロパティではアンエスケープされたものを返し、 `Status#textRaw`, `Status#fullTextRaw` プロパティではレスポンスの値をそのまま返すように変更したいと思います。
インデックスで参照したい場合には `Status#textRaw`, `Status#fullTextRaw` をご利用ください。

**Comment by SlashNephy** [comment]
遅くなりましたが修正版 6.2.1 をリリースしました。Maven Central 反映には1時間ほど掛かるはずです。
