### ISSUE TITLE
Should have `userTimelineByScreenName()` in the README?

### ISSUE THREAD

**Issue by johnjacobkenny** [StarryBlueSky/Penicillin#38]
I was trying the example in the README and Intellij gave me an error saying that the `screenName` was not applicable. Looking at the documentation, I found that `userTimelineByScreenName()` works.

Should this be updated in the README? Thanks

**Comment by SlashNephy** [comment]
Thanks for the report, I fixed the README.

https://github.com/StarryBlueSky/Penicillin/pull/40
